version: "3"
services:
  db:
    container_name: pimseis-db
    image: mysql:8.0.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ad1m@d1m%2024
    volumes:
      - ./database/data:/var/lib/mysql
    platform: linux/x86_64
    networks:
      - pimseis

  phpmyadmin:
    container_name: pimseis-phpmyadmin
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: "512M"
    links:
      - db
    networks:
      - pimseis

networks:
  pimseis:
    driver: bridge
